language: python
jobs:
  include:
    - os: linux
      python: 3.6
      env: TOXENV=py36
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: linux
      python: 3.8
      env: TOXENV=py38
    - os: linux
      python: 2.7
      env: TOXENV=py27

install:
  - pip install tox
script: tox
branches:
  only:
    - master
notifications:
  email: false