language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - TOXENV=py27
  - TOXENV=py36
  - TOXENV=py37
  - TOXENV=py38
  - TOXENV=sqla9
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=lint
  - TOXENV=coverage
install:
  - "pip install tox"
# command to run tests
script: tox
branches:
  only:
    - master
notifications:
  email: false