language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install pipenv
  - pipenv install
# command to run tests
script: pipenv run python -m pytest
branches:
  only:
    - master
notifications:
  email: false